import {
  REQUEST_METHOD_GET,
  REQUEST_METHOD_POST,
  REQUEST_METHOD_PUT,
  REQUEST_METHOD_PATCH,
  REQUEST_METHOD_DELETE,
  REQUEST_METHOD_OPTIONS,
  REQUEST_METHOD_HEAD,
  REQUEST_METHOD_CONNECT,
  REQUEST_METHOD_TRACE,
} from './methods';

export const requestMethods = [
  REQUEST_METHOD_GET,
  REQUEST_METHOD_POST,
  REQUEST_METHOD_PUT,
  REQUEST_METHOD_PATCH,
  REQUEST_METHOD_DELETE,
  REQUEST_METHOD_OPTIONS,
  REQUEST_METHOD_HEAD,
  REQUEST_METHOD_CONNECT,
  REQUEST_METHOD_TRACE,
] as const;

export type RequestMethod = typeof requestMethods[number];
